services:                                                                                                                            
  postgres-users:                                                                                                                    
    image: postgres:16
    container_name: postgres-users
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres                                                                                                        
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db 
  postgres-orders:                                                                                                                    
    image: postgres:16
    container_name: postgres-orders
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres                                                                                                        
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db 
  user-service:                                                                                                                 
      build: ./user-service                                                                                                            
      container_name: user-service                                                                                                     
      ports:                                                                                                                           
        - "3001:3001"                                                                                                                  
      environment:
        PORT: 3001                                                                                                                     
        DB_HOST: postgres-users
        DB_PORT: 5432                                                                                                                  
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DB_NAME: users_db                                                                                                              
      depends_on:
        - postgres-users                                                                                                               
  order-service:
    build:
      context: .                                                                                                                                      
      dockerfile: order-service/Dockerfile
    container_name: order-service
    environment:
      PORT: 3002                                                                                                                     
      DB_HOST: postgres-orders
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: orders_db
      USER_SERVICE_URL: http://user-service:3001
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      INVENTORY_SERVICE_URL: inventory-service:5000                                                                          
    depends_on:
      - postgres-orders                                                                                                              
      - user-service
      - rabbitmq
      - inventory-service
  rabbitmq:                                                                                                                          
    image: rabbitmq:3-management                                                                                                     
    container_name: rabbitmq                                                                                                         
    ports:                                                                                                                           
      - "5672:5672"                                                                                                                  
      - "15672:15672"
  notification-service:                                                                                                              
    build: ./notification-service                                                                                                    
    container_name: notification-service                                                                                             
    environment:                                                                                                                     
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672                                                                                 
    depends_on: 
      - rabbitmq
  payment-service:
    build: ./payment-service
    container_name: payment-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
  saga-orchestrator:
    build: ./saga-orchestrator
    container_name: saga-orchestrator
    environment:
      PORT: 3003
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      DB_HOST: postgres-auth
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      JWT_SECRET: your-secret-key
    depends_on:
      - postgres-auth
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3005:3000"
    environment:
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3004
      USER_SERVICE_URL: http://user-service:3001
      ORDER_SERVICE_URL: http://order-service:3002
      SAGA_SERVICE_URL: http://saga-orchestrator:3003
      JWT_SECRET: your-secret-key
    depends_on:
      - auth-service
      - user-service
      - order-service
      - saga-orchestrator
  inventory-service:                                                                                                              
    build:                                                                                                                                            
      context: .                                                                                                                                      
      dockerfile: inventory-service/Dockerfile                                                                                                                       
    container_name: inventory-service                                                                                                                 
    environment:                                                                                                                                      
      GRPC_PORT: 5000
